language: bash

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - bash-completion

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bash-completion@2 gnu-getopt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/{opt/gnu-getopt/,}bin:$PATH"; fi

script:
  - ./tests/test
